// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetosPessoais.Repositorio.Database.Contexto;

namespace ProjetosPessoais.Repositorio.Database.Migrations
{
    [DbContext(typeof(ProjetosPessoaisContexto))]
    [Migration("20200121011032_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.ContasPagar.BancosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodBanco")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bancos","contapagar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodBanco = "001",
                            Descricao = "Banco do Brasil S.A.",
                            Guid = new Guid("770603c5-d640-4fed-ac57-af71280fe913")
                        },
                        new
                        {
                            Id = 2,
                            CodBanco = "341",
                            Descricao = "Itaú S.A",
                            Guid = new Guid("71507bb8-3f46-4133-aed1-89f2225c792a")
                        },
                        new
                        {
                            Id = 3,
                            CodBanco = "033",
                            Descricao = "Santander",
                            Guid = new Guid("78b422fb-fb0e-4ffe-877b-337c6eace195")
                        },
                        new
                        {
                            Id = 4,
                            CodBanco = "237",
                            Descricao = "Banco Bradesco S.A.",
                            Guid = new Guid("f9f26ba3-b888-45ff-b2e8-08bf9fe8e21d")
                        },
                        new
                        {
                            Id = 5,
                            CodBanco = "104",
                            Descricao = "Caixa Econômica Federal",
                            Guid = new Guid("547028a5-0463-4061-b17a-b4a774737f98")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
