// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetosPessoais.Repositorio.Database.Contexto;

namespace ProjetosPessoais.Repositorio.Database.Migrations
{
    [DbContext(typeof(ProjetosPessoaisContexto))]
    [Migration("20200121022303_AlteracaoTipoDataTabelaCompromisso")]
    partial class AlteracaoTipoDataTabelaCompromisso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.Calendario.CompromissosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCompromisso")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Calendario","compromissos");
                });

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.ContasPagar.BancosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodBanco")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bancos","contapagar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodBanco = "001",
                            Descricao = "Banco do Brasil S.A.",
                            Guid = new Guid("2a0c2920-e59b-4b5d-9f44-86a2438371b4")
                        },
                        new
                        {
                            Id = 2,
                            CodBanco = "341",
                            Descricao = "Itaú S.A",
                            Guid = new Guid("26899535-d1fd-49bd-8c6a-8a88efd7da7b")
                        },
                        new
                        {
                            Id = 3,
                            CodBanco = "033",
                            Descricao = "Santander",
                            Guid = new Guid("6a3ca4be-6997-41ea-b4f1-dcbba4d97207")
                        },
                        new
                        {
                            Id = 4,
                            CodBanco = "237",
                            Descricao = "Banco Bradesco S.A.",
                            Guid = new Guid("5e345ced-8498-4b1e-a0bc-77dc52e805ae")
                        },
                        new
                        {
                            Id = 5,
                            CodBanco = "104",
                            Descricao = "Caixa Econômica Federal",
                            Guid = new Guid("22a695db-618c-4e2f-8721-9d876f9cd226")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
