// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetosPessoais.Repositorio.Database.Contexto;

namespace ProjetosPessoais.Repositorio.Database.Migrations
{
    [DbContext(typeof(ProjetosPessoaisContexto))]
    [Migration("20200121021039_DesenvolvimentoFuncoesDeCalendario")]
    partial class DesenvolvimentoFuncoesDeCalendario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.Calendario.CompromissosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Calendario","compromissos");
                });

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.ContasPagar.BancosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodBanco")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bancos","contapagar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodBanco = "001",
                            Descricao = "Banco do Brasil S.A.",
                            Guid = new Guid("ecf874f1-8a05-4daa-936e-5161145d6cf4")
                        },
                        new
                        {
                            Id = 2,
                            CodBanco = "341",
                            Descricao = "Itaú S.A",
                            Guid = new Guid("59b66633-f2db-42c2-82a6-33292cc3f056")
                        },
                        new
                        {
                            Id = 3,
                            CodBanco = "033",
                            Descricao = "Santander",
                            Guid = new Guid("305b236a-df44-42da-a829-1456c020f6b7")
                        },
                        new
                        {
                            Id = 4,
                            CodBanco = "237",
                            Descricao = "Banco Bradesco S.A.",
                            Guid = new Guid("ff97df7c-0cc7-4138-85c2-3c1919e7026b")
                        },
                        new
                        {
                            Id = 5,
                            CodBanco = "104",
                            Descricao = "Caixa Econômica Federal",
                            Guid = new Guid("28458097-4258-404b-bbab-f7aac868e055")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
