// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetosPessoais.Repositorio.Database.Contexto;

namespace ProjetosPessoais.Repositorio.Database.Migrations
{
    [DbContext(typeof(ProjetosPessoaisContexto))]
    [Migration("20200121023115_RemocaoCampoHorarioTabelaCompromisso")]
    partial class RemocaoCampoHorarioTabelaCompromisso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.Calendario.CompromissosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCompromisso")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Calendario","compromissos");
                });

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.ContasPagar.BancosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodBanco")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bancos","contapagar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodBanco = "001",
                            Descricao = "Banco do Brasil S.A.",
                            Guid = new Guid("fdc72818-8d66-4527-bef6-14d011ff556f")
                        },
                        new
                        {
                            Id = 2,
                            CodBanco = "341",
                            Descricao = "Itaú S.A",
                            Guid = new Guid("9fe867a9-fe59-4150-aa2e-01f723de7e31")
                        },
                        new
                        {
                            Id = 3,
                            CodBanco = "033",
                            Descricao = "Santander",
                            Guid = new Guid("059a1218-9a8d-4a45-8b04-226f5dc49d84")
                        },
                        new
                        {
                            Id = 4,
                            CodBanco = "237",
                            Descricao = "Banco Bradesco S.A.",
                            Guid = new Guid("7bc0cb01-c15b-4a48-a5fd-f0ab313067c8")
                        },
                        new
                        {
                            Id = 5,
                            CodBanco = "104",
                            Descricao = "Caixa Econômica Federal",
                            Guid = new Guid("c321180e-1733-479d-b585-d5cd922260b6")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
