// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetosPessoais.Repositorio.Database.Contexto;

namespace ProjetosPessoais.Repositorio.Database.Migrations
{
    [DbContext(typeof(ProjetosPessoaisContexto))]
    [Migration("20200214022656_DesenvolvidoTokenEUsuario")]
    partial class DesenvolvidoTokenEUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.Calendario.CompromissosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCompromisso")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Calendario","compromissos");
                });

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.ContasPagar.BancosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodBanco")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bancos","contapagar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodBanco = "001",
                            Descricao = "Banco do Brasil S.A.",
                            Guid = new Guid("fe1ca0b9-1ebb-4f07-8c42-0c2f4da22f34")
                        },
                        new
                        {
                            Id = 2,
                            CodBanco = "341",
                            Descricao = "Itaú S.A",
                            Guid = new Guid("d73a6bf6-b176-4f52-9b27-4e94c582f5a0")
                        },
                        new
                        {
                            Id = 3,
                            CodBanco = "033",
                            Descricao = "Santander",
                            Guid = new Guid("bc560e93-19de-4fab-b3c1-8a35e1eb0822")
                        },
                        new
                        {
                            Id = 4,
                            CodBanco = "237",
                            Descricao = "Banco Bradesco S.A.",
                            Guid = new Guid("cf62b69f-d0a4-49a8-acfe-1c794369f43c")
                        },
                        new
                        {
                            Id = 5,
                            CodBanco = "104",
                            Descricao = "Caixa Econômica Federal",
                            Guid = new Guid("0329b07d-de03-4688-9b51-2b048061d5a1")
                        });
                });

            modelBuilder.Entity("ProjetosPessoais.Dominio.Entidades.Usuario.UsuariosEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios","autenticacao");
                });
#pragma warning restore 612, 618
        }
    }
}
